data agsrs;
 infile 'C:\Users\Administrador\Documents\My SAS Files\V8\agsrs.csv' delimiter=';' firstobs=2;
 input country  $ state $ acres92 acres87 acres82 farms92 farms87 farms82 largef92 largef87 largef82 smallf92 smallf87 smallf82;
 run;
 proc print data=agsrs;
 run;
 proc corr data=agsrs;
 run;
 data agsrs2;
 set agsrs;
 keep country state acres92;
 run;
 proc print data=agsrs2;
 run;
 data agsrs3;
 set agsrs;
 drop acres82 farms92 farms82 largef92 largef87 largef82;
 incremento=acres92-acres87;
 if acres92>297897 then tamano="grande  ";
 else tamano="pequeño";
 run;
 proc print data=agsrs3;
 run;
 data tx;
 set agsrs3;
 if state='TX';
 run;
 proc print data=tx;
 run;
 proc gplot data=agsrs3;
 plot acres92 * acres87; * eje y: acres92, ejex: acres87; 
 run;
 data txga;
 set agsrs3;
 if state='TX' or state="GA";
 run;
 proc print data=txga;
 run; 
symbol1;
 symbol1 v=square;
 symbol2 v=triangle;
 proc gplot;
 plot acres92* acres87=state;
 run;
 proc univariate data=agsrs3;
 var acres92 acres87;
 histogram acres92 acres87/normal;
 probplot acres92 acres87;
 run;
